In [17]:
print("Welcome to Data Mining Lab!")

name = "Alice"
age = 22
cgpa = 3.85
is_student = True

print(name)
print(age)
print(cgpa)
print(is_student)

Welcome to Data Mining Lab!
Alice
22
3.85
True

In [18]:
a = 10
b = 3.5
c = "Data Mining"
d = False

print(type(a))
print(type(b))
print(type(c))
print(type(d))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>

In [19]:
x = 20
y = 7

print("Addition:", x + y)
print("Subtraction:", x - y)
print("Multiplication:", x * y)
print("Division:", x / y)
print("Floor Division:", x // y)
print("Modulus:", x % y)
print("Power:", x ** y)

Addition: 27
Subtraction: 13
Multiplication: 140
Division: 2.857142857142857
Floor Division: 2
Modulus: 6
Power: 1280000000

In [20]:
marks = [85, 90, 78, 95, 88]

print(marks)

print("First:", marks[0])
print("Last:", marks[-1])

marks.append(100)

print(marks)

marks.remove(78)

print(marks)

print("Length:", len(marks))

[85, 90, 78, 95, 88]
First: 85
Last: 88
[85, 90, 78, 95, 88, 100]
[85, 90, 95, 88, 100]
Length: 5

In [21]:
colors = ("Red", "Green", "Blue")

print(colors)

print(colors[1])

('Red', 'Green', 'Blue')
Green

In [22]:
student = {
    "Name": "Alice",
    "Age": 22,
    "CGPA": 3.90
}

print(student)

print(student["Name"])

student["Department"] = "CSE"

print(student)

{'Name': 'Alice', 'Age': 22, 'CGPA': 3.9}
Alice
{'Name': 'Alice', 'Age': 22, 'CGPA': 3.9, 'Department': 'CSE'}

In [23]:
marks = 75

if marks >= 80:
    print("Grade A")
elif marks >= 70:
    print("Grade B")
elif marks >= 60:
    print("Grade C")
else:
    print("Fail")

Grade B

In [24]:
numbers = [5, 10, 15, 20]

for num in numbers:
    print(num)

5
10
15
20

In [25]:
i = 1

while i <= 5:
    print(i)
    i += 1

1
2
3
4
5

In [26]:
def square(x):
    return x * x

print(square(5))
print(square(9))

25
81

In [27]:
import numpy as np
import pandas as pd

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [28]:
arr = np.array([10, 20, 30, 40, 50])

print(arr)

print(arr + 5)

print(arr * 2)

print(np.mean(arr))

print(np.max(arr))

print(np.min(arr))

[10 20 30 40 50]
[15 25 35 45 55]
[ 20  40  60  80 100]
30.0
50
10

In [29]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [22, 23, 21, 22],
    "CGPA": [3.9, 3.5, 3.7, 3.8]
}

df = pd.DataFrame(data)

df

      Name  Age  CGPA
0    Alice   22   3.9
1      Bob   23   3.5
2  Charlie   21   3.7
3    David   22   3.8

In [30]:
print(df.head())
print()

print(df.tail())
print()

print(df.shape)
print()

print(df.columns)
print()

print(df.info())
print()

print(df.describe())

      Name  Age  CGPA
0    Alice   22   3.9
1      Bob   23   3.5
2  Charlie   21   3.7
3    David   22   3.8

      Name  Age  CGPA
0    Alice   22   3.9
1      Bob   23   3.5
2  Charlie   21   3.7
3    David   22   3.8

(4, 3)

Index(['Name', 'Age', 'CGPA'], dtype='object')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   CGPA    4 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 228.0+ bytes
None

             Age      CGPA
count   4.000000  4.000000
mean   22.000000  3.725000
std     0.816497  0.170783
min    21.000000  3.500000
25%    21.750000  3.650000
50%    22.000000  3.750000
75%    22.250000  3.825000
max    23.000000  3.900000

In [37]:
print(df["Name"])
print()

print(df[["Name", "CGPA"]])

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object

      Name  CGPA
0    Alice  3.90
1      Bob  3.95
2  Charlie  3.70
3    David  3.80

In [38]:
print(df.iloc[0])
print()

print(df.iloc[1:3])

Name      Alice
Age          22
CGPA        3.9
Passed     True
Name: 0, dtype: object

      Name  Age  CGPA  Passed
1      Bob   23  3.95    True
2  Charlie   21  3.70    True

In [33]:
high_cgpa = df[df["CGPA"] > 3.7]

high_cgpa

    Name  Age  CGPA
0  Alice   22   3.9
3  David   22   3.8

In [34]:
df["Passed"] = True

df

      Name  Age  CGPA  Passed
0    Alice   22   3.9    True
1      Bob   23   3.5    True
2  Charlie   21   3.7    True
3    David   22   3.8    True

In [35]:
df.loc[1, "CGPA"] = 3.95

df

      Name  Age  CGPA  Passed
0    Alice   22  3.90    True
1      Bob   23  3.95    True
2  Charlie   21  3.70    True
3    David   22  3.80    True

In [40]:
df.sort_values("CGPA", ascending=False)

      Name  Age  CGPA  Passed
1      Bob   23  3.95    True
0    Alice   22  3.90    True
3    David   22  3.80    True
2  Charlie   21  3.70    True